"use strict";

const DOCUMENT_TYPE_VARIABLES = Object.create(null);

module.exports = Object.assign(DOCUMENT_TYPE_VARIABLES, {
    PLAIN_TEXT: "PLAIN_TEXT",
    DOUBLE_ANNOTATED_TEXT: "DOUBLE_ANNOTATED_TEXT",
    ANNOTATED_TEXT: "ANNOTATED_TEXT",
    STRUCTURED_TEXT: "STRUCTURED_TEXT",
    POWER_POINT: "POWER_POINT",
});
